site_name: Ktorceful
repo_name: ktorceful
repo_url: https://github.com/herrrta/ktorceful
site_description: A simple solution to create reusable class based routing for Ktor
remote_branch: gh-pages

theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'blue-grey'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - announce.dismiss

plugins:
  - search

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 'Home': index.md
  - 'Setup': setup.md
  - 'Basic Routing':
      - 'Overview': core/index.md
      - 'Kotlin API': api/core/index.html
  - 'Entity Routing':
      - 'Overview': dao/index.md
      - 'Actions': dao/actions.md
      - 'Kotlin API': api/dao/index.html
  - 'Auth':
      - 'Overview': auth/index.md
      - 'Kotlin API': api/auth/index.html
  - 'Samples': samples.md
  - 'Kotlin API': api/index.html