name: Docs Publish
on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: Docs Publish
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Dokka HTML
        run: |
          ./gradlew dokkaHtmlMultiModule

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Build mkdocs
        run: |
          pip3 install -r .github/workflows/mkdocs-requirements.txt
          mkdocs build

      - name: Deploy 🚀
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          folder: site
          branch: gh-pages